# This file was automatically generated by bifcl from events.bif.

export {
global pdf_info: event(f: fa_file , info: PDF::Info );

global pdf_too_large: event(f: fa_file );

global pdf_error: event(f: fa_file , e: PDF::Error );

} # end of export section
module GLOBAL;
